version: '3.1'
services:
  mysql:
    container_name: mysql
    image: mysql
    restart: unless-stopped
    environment:
      - MYSQL_MULTIPLE_DATABASES=dev,prod
      - MYSQL_ROOT_PASSWORD=$MYSQL_ROOT_PASSWORD
      - MYSQL_USER=$MYSQL_USER
      - MYSQL_PASSWORD=$MYSQL_PASSWORD
      - TZ=Asia/Seoul
    volumes:
      - ./db/mysql/data:/var/lib/mysql
      - ./db/mysql/config:/etc/mysql/conf.d
      - ./db/mysql/init:/docker-entrypoint-initdb.d
    networks:
      - npm-network
    
  adminer:
    container_name: adminer
    image: adminer
    restart: unless-stopped
    environment:
      - TZ=Asia/Seoul
    ports:
      - 8484:8080
    networks:
      - npm-network
      
networks:
  npm-network:
    external: true
    name: npm-network