version: "3.8"

services:
  redis:
    image: redis:7.2.4-alpine
    container_name: redis
    privileged: true
    command:
      - /bin/sh
      - -c
      - |
        sysctl vm.overcommit_memory=1
        exec redis-server /usr/local/etc/redis/redis.conf --requirepass ${REDIS_PASSWORD}
    volumes:
      - ./redis/data:/data
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
    restart: always
    environment:
      - TZ=Asia/Seoul
    networks:
      - npm-network
      
networks:
  npm-network:
    external: true
    name: npm-network